FROM debian:buster

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y php \
            php-fpm \
            php-cli \
            php-mysqli \
            php-json \
            php-mbstring \
            php-curl \
            mariadb-client \
            wget

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp
RUN mkdir -p /run/php

RUN sed -i "s|listen = /run/php/php7.3-fpm.sock|listen = 9000|g" /etc/php/7.3/fpm/pool.d/www.conf
COPY ./tools/wp_script.sh /
RUN chmod +x /wp_script.sh

WORKDIR /var/www/html/wordpress

ENTRYPOINT [ "sh", "/wp_script.sh" ]