FROM debian:buster

RUN apt update -y && apt-get upgrade -y &&  apt install -y mariadb-server

RUN mkdir -p /var/run/mysqld \
   && chown -R mysql:mysql /run/mysqld \
   && chmod 777 /run/mysqld

COPY 50-server.cnf   /etc/mysql/mariadb.conf.d/50-server.cnf

RUN ln -sf /etc/mysql/mariadb.conf.d/50-server.cnf /etc/mysql/my.cnf
COPY  mariadb_conf.sh .

RUN chmod +x mariadb_conf.sh

EXPOSE 3306

ENTRYPOINT ["bash","./mariadb_conf.sh"]