FROM alpine:3.18

RUN apk update && \
	apk upgrade && \
	apk add php \
			php-fpm \
			php-cli \
			php-mysqli \
			php-json \
			php-phar \
			php-mbstring \
			php-curl \
			mariadb-client

ENV DB_HOST=db
ENV WP_DB_USER=wordpressuser
ENV WP_DB_PASS=wordpresspassword
ENV WP_DB_NAME=wordpress
ENV WP_PATH=/var/www/html/wordpress
ENV NGINX_HOST=localhost
ENV WP_TITLE=WordPress
ENV WP_ADMIN_USER=admin
ENV WP_ADMIN_PASS=adminpassword
ENV WP_ADMIN_EMAIL=admin@example.com
ENV WP_USER=user
ENV WP_USER_EMAIL=user@example.com
ENV WP_USER_PASS=userpassword

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && \
	mv wp-cli.phar /usr/local/bin/wp

RUN sed -i "s|listen = 127.0.0.1:9000|listen = 9000|g" /etc/php81/php-fpm.d/www.conf

COPY wp_conf.sh /tmp/wp_conf.sh

WORKDIR /var/www/html/wordpress

ENTRYPOINT [ "sh", "/tmp/wp_conf.sh" ]
