FROM debian:buster

RUN apt -y update && apt -y upgrade
RUN apt install -y  wget \
                    vim \
                    php-fpm \
                    php-mysql \
					sendmail \
                    mariadb-client

COPY wordpress.sh /usr/local/bin/wordpress.sh
RUN chmod +x  /usr/local/bin/wordpress.sh



ENTRYPOINT ["/usr/local/bin/wordpress.sh"]
CMD ["php-fpm7.3", "-F"]