FROM alpine:3.18

RUN apk update && \
    apk upgrade && \
    apk add nginx \
            openssl

COPY script.sh /
COPY default.conf /etc/nginx/http.d/default.conf

EXPOSE 443

ENTRYPOINT [ "sh", "/script.sh" ]