FROM debian:12.5

RUN apt-get update &&  apt-get upgrade -y && \
    apt-get install -y nginx && \
    apt-get install -y vim curl openssl

RUN mkdir -p /var/run/nginx
RUN chmod 755 -R /var/www/html/
COPY default.conf /etc/nginx/default.conf

RUN chmod 755 -R /var/www/html  && \
    chown -R www-data:www-data /var/www/html

EXPOSE 443
EXPOSE 80
 # Start NGINX
CMD ["nginx", "-g", "daemon off;"]