FROM debian:buster

# Set environment variables for database configuration
ENV DATABASE_ROOT_PASSWORD=root
ENV DATABASE_NAME=wordpress
ENV DATABASE_USER=user_database
ENV DATABASE_USER_PASSWORD=user_password

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install -y 	mariadb-server \
			vim \
			procps

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY script.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/script.sh

EXPOSE 3306

ENTRYPOINT ["/docker-entrypoint-initdb.d/script.sh"]

CMD ["mysqld_safe"]
