FROM alpine:3.18

RUN apk update && \
	apk upgrade && \
	apk add mariadb \
			mariadb-client

ENV DB_ROOT_PASS=root
ENV WP_DB_NAME=wordpress
ENV WP_DB_USER=user
ENV WP_DB_PASS=word
COPY mariadb_conf.sh /tmp/mariadb_conf.sh

EXPOSE 3306

ENTRYPOINT [ "sh", "/tmp/mariadb_conf.sh" ]
