FROM debian:buster

RUN apt-get update && \
    apt-get install mariadb-server -y

#mkdir -p /run/mysqld
	#chown -R mysql:mysql /run/mysqld
COPY 50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY script.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/script.sh

# Create directory for MySQL socket file and set permissions


# Expose MySQL port
EXPOSE 3306

ENTRYPOINT ["sh","/docker-entrypoint-initdb.d/script.sh"]