version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx/
    image: nginx:42
    ports:
      - "80:80"
    volumes:
      - wp-data:/var/www/html/wordpress
    restart: on-failure
    networks:
      - inception
    depends_on:
      - mariadb
      - wordpress

  mariadb:
    container_name: mariadb
    build: ./mariadb/
    image: mariadb:42
    env_file: .env
    restart: on-failure
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
    
  wordpress:
    container_name: wordpress
    build: ./wordpress/
    image: wordpress:42
    env_file: .env
    restart: on-failure
    volumes:
      - wp-data:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      
networks:
  inception:
    driver: bridge

volumes:
  db-data:
  wp-data:

